version: "3.5"
networks:
  default:
    name: xgon
services:
  xgon-rpc:
    container_name: xgon-rpc
    restart: unless-stopped
    depends_on:
      xgon-pool-db:
        condition: service_healthy
      xgon-state-db:
        condition: service_healthy
      xgon-sync:
        condition: service_started
    image: okexchain/xgon-node:origin_release_v0.1.0_20231107071509
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - 8545:8545
      - 9091:9091 # needed if metrics enabled
    environment:
      - XGON_NODE_ETHERMAN_URL=${XGON_NODE_ETHERMAN_URL}
    volumes:
      - ${XGON_ADVANCED_CONFIG_DIR:-./config/environments/${XGON_NETWORK}}/node.config.toml:/app/config.toml
      - ${XGON_ADVANCED_CONFIG_DIR:-./config/environments/${XGON_NETWORK}}/genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xgon-node run --network ${XGON_NETWORK} --cfg /app/config.toml --components rpc"

  xgon-sync:
    container_name: xgon-sync
    restart: unless-stopped
    depends_on:
      xgon-state-db:
        condition: service_healthy
    image: okexchain/xgon-node:origin_release_v0.1.0_20231107071509
    ports:
      - 9092:9091 # needed if metrics enabled
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - XGON_NODE_ETHERMAN_URL=${XGON_NODE_ETHERMAN_URL}
    volumes:
      - ${XGON_ADVANCED_CONFIG_DIR:-./config/environments/${XGON_NETWORK}}/node.config.toml:/app/config.toml
      - ${XGON_ADVANCED_CONFIG_DIR:-./config/environments/${XGON_NETWORK}}/genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xgon-node run --network ${XGON_NETWORK} --cfg /app/config.toml --components synchronizer"

  xgon-state-db:
    container_name: xgon-state-db
    restart: unless-stopped
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./db/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ${XGON_NODE_STATEDB_DATA_DIR}:/var/lib/postgresql/data
      - ${XGON_ADVANCED_CONFIG_DIR:-./config/environments/${XGON_NETWORK}}/postgresql.conf:/etc/postgresql.conf
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command:
      - "postgres"
      - "-N"
      - "500"
      - "-c"
      - "config_file=/etc/postgresql.conf"

  xgon-pool-db:
    container_name: xgon-pool-db
    restart: unless-stopped
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    volumes:
      - ${XGON_NODE_POOLDB_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xgon-prover:
    container_name: xgon-prover
    restart: unless-stopped
    image: okexchain/xgon-prover:origin_release_v0.1.0_20231017143028
    depends_on:
      xgon-state-db:
        condition: service_healthy
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ${XGON_ADVANCED_CONFIG_DIR:-./config/environments/${XGON_NETWORK}}/prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
